### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by M5oul**
- [Manually force level 4](https://github.com/YunoHost/package_check#-levels).
- Linter is :ok: which validate level 5
- [fix] Remove double `firewall allow`.
- [fix] Modify configuration file, and then move it.
- set myself as maintainer.

---
The app [should go level 6](https://ci-apps.yunohost.org/jenkins/job/mumbleserver%20(Community)/lastBuild/consoleFull) and could pretend [official integration](https://github.com/YunoHost-Apps/mumbleserver_ynh/issues/10).

### CODE REVIEW

**Review by frju365 — DISMISSED** [review]
It's good. But it's better to add an issue for `Level 4=1` + add the URL of the issue in the 'check_process' file.
For the  maintainer, perhaps it's better to have the name of the original maintainer of the package somewhere in the manifest or at least in comment (#).

**Comment by M5oul** [comment]
> It's good. But it's better to add an issue for Level 4=1 + add the URL of the issue in the 'check_process' file.

Ok, I will do that.

> For the maintainer, perhaps it's better to have the name of the original maintainer of the package somewhere in the manifest or at least in comment (#).

For the original contributor, his contact is on git commits. For me it's enough.
We could create a file containing Contributors. I won't do it as `git commits` say enough about work history of the repository.

**Comment by maniackcrudelis** [comment]
Hum, the level 6 is reached only because yunohost return 0 even if the backup and restore are clearly failed !
And with a blank upgrade script, I should say that this app is only reaching the level 2...

Also, for official integration, some things are missing.

- Use more helpers. YEP 2.12
- Use a real ;) upgrade script.
- And also have backup and restore script for the level 6.
- The test with the port obviously fail, because your script has to fail if the port is not available

---
If you need some help, don't hesitate :)

**Comment by M5oul** [comment]
Any review on this one?
@frju365 ok for you now?

**Comment by JimboJoe** [comment]
After reviewing it, I think @maniackcrudelis said it all. Moreover as a newer official app, it would be much better (expected?) to comply with the latest template (pending PRs on example_ynh).
I understand these reviews are a bit harsh to read so feel free to raise your voice if needed :-)

**Comment by M5oul** [comment]
Any approval for this MR?
It only updates the package.
For official integration, we will see later. Let's use #10 for that.

**Review by maniackcrudelis — APPROVED** [review]

**Comment by maniackcrudelis** [comment]
I just read the code, but I have already do a check earlier.
So, ok for me for an upgrade.

**Pull request merged**
