### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by Jibec**
Hi, please review this, if this looks fine to you, I'll write an upgrade script

### CODE REVIEW

**Review by JimboJoe — APPROVED** [review]
For what it's worth, that looks fine to me 👍

**Comment by Jibec** [comment]
OK thanks, so it worth creating an upgrade script :)

Can you please elaborate your test? Platform and parameters.
-- 
Jean-Baptiste Holcroft

**Comment by JimboJoe** [comment]
Well, I only reviewed the code 😊

**Comment by Jibec** [comment]
Please test upgrade from older versions.

@M5oul is it ok for you if I put my name as a maintainer for this app? I'll add yours like I did for kanboard: https://github.com/YunoHost-Apps/kanboard_ynh/pull/62/files

**Comment by Jibec** [comment]
BTW, this apps is now lvl 7 :)

**Comment by M5oul** [comment]
Go ahead!

**Comment by Jibec** [comment]
done :)

can you please?
* test a migration from old to new app
* add me as owner of this repository

**Comment by M5oul** [comment]
I created a Mumble team with three of us in it.

**Comment by Jibec** [comment]
that's a fine solution!

**Pull request merged**
